### ISSUE TITLE
공격적인 성향의 차량 셋팅

### ISSUE THREAD

**Issue by optimus5383** [IITP-Load-Balancing-SMEET/IITP-Load-Balancing-SMEET#3]
현재 공격적인 차량으로 opendrive에 설정된 제한 속도 이상으로 주행하게 설정했습니다. 
차선이나 추가 요인 고려 필요해보입니다.

**Comment by soup1997** [comment]
OpenScenario상에서 속도 파싱해서 제한속도 설정하는 코드 추가 완료 했습니다.
